import * as Types from '@/gql/generated/types';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type AllPeopleQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type AllPeopleQuery = { __typename?: 'Root', allPeople: { __typename?: 'PeopleConnection', totalCount: number | null, people: Array<{ __typename?: 'Person', id: string, name: string | null, gender: string | null, birthYear: string | null, species: { __typename?: 'Species', name: string | null } | null, homeworld: { __typename?: 'Planet', name: string | null } | null } | null> | null } | null };

export type SinglePeopleQueryVariables = Types.Exact<{
  id: Types.InputMaybe<Types.Scalars['ID']['input']>;
}>;


export type SinglePeopleQuery = { __typename?: 'Root', person: { __typename?: 'Person', id: string, name: string | null, gender: string | null, birthYear: string | null, eyeColor: string | null, height: number | null, mass: number | null, species: { __typename?: 'Species', id: string, name: string | null } | null, homeworld: { __typename?: 'Planet', id: string, name: string | null, population: number | null, diameter: number | null, rotationPeriod: number | null, orbitalPeriod: number | null, gravity: string | null } | null, filmConnection: { __typename?: 'PersonFilmsConnection', films: Array<{ __typename?: 'Film', title: string | null, releaseDate: string | null } | null> | null } | null } | null };


export const AllPeopleDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"AllPeople"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"allPeople"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"totalCount"}},{"kind":"Field","name":{"kind":"Name","value":"people"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"gender"}},{"kind":"Field","name":{"kind":"Name","value":"birthYear"}},{"kind":"Field","name":{"kind":"Name","value":"species"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"name"}}]}},{"kind":"Field","name":{"kind":"Name","value":"homeworld"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"name"}}]}}]}}]}}]}}]} as unknown as DocumentNode<AllPeopleQuery, AllPeopleQueryVariables>;
export const SinglePeopleDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"SinglePeople"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"person"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"gender"}},{"kind":"Field","name":{"kind":"Name","value":"birthYear"}},{"kind":"Field","name":{"kind":"Name","value":"species"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}},{"kind":"Field","name":{"kind":"Name","value":"homeworld"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"population"}},{"kind":"Field","name":{"kind":"Name","value":"diameter"}},{"kind":"Field","name":{"kind":"Name","value":"rotationPeriod"}},{"kind":"Field","name":{"kind":"Name","value":"orbitalPeriod"}},{"kind":"Field","name":{"kind":"Name","value":"gravity"}}]}},{"kind":"Field","name":{"kind":"Name","value":"filmConnection"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"films"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"title"}},{"kind":"Field","name":{"kind":"Name","value":"releaseDate"}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"eyeColor"}},{"kind":"Field","name":{"kind":"Name","value":"height"}},{"kind":"Field","name":{"kind":"Name","value":"mass"}}]}}]}}]} as unknown as DocumentNode<SinglePeopleQuery, SinglePeopleQueryVariables>;